### ISSUE TITLE
missing little n  ?   m/[^atgcATGCN]/)

### ISSUE THREAD

**Issue by tseemann** [jizhang-nz/fast-GeP#10]
```
          if($extraction =~ m/[^atgcATGCN]/){
            $presences["$key"] = "9"; #9 code for containing ambiguity codes
          }elsif($extraction =~ m/N/){
```

I notice lowercase `n` is not included - is that a mistake?

maybe use `m/[^ATGCN]/i` and `m/N/i` # i = case insensitive

**Comment by maesaar** [comment]
Could this missing lowercase “n” influence the final results?

**Comment by jizhang-nz** [comment]
Hi tseemann,
Thanks for the comment. The "n" was intentionally left out in line 375. 
If you look at line 141 and the context:
`			$seq =~ s/N/n/g;`
you might notice that the "N" and "n" were treated differently in processing the sequences. The "N" denote for the spacer sequence in concatenating the contigs, whereas the "n" is the true ambiguity code presented in the original data.

mmaesaar: this is not a bug thus won't influence the results.

I hope my explanation is clear enough.
Cheers,
Ji

**Comment by tseemann** [comment]
Ok thank you. 
 Why do you need to concatenate the contigs?
Do you risk false blast/diamond results that cross the`n` ?

**Comment by jizhang-nz** [comment]
Hi tseemann,
I'd prefer to concatenate the contigs because it's a more efficient way to process draft genome sequences.
Your second question is a very good point. However I don't worry about the risk as the code will do two things to prevent it from happening:
1. use long enough spacer sequences (default 200 "N") to connect the contigs;
2. even if the spacer "N" somehow find a way into the alignments, the code would be able to recognize it by treating "N" and "n" differently.

Cheers,
Ji
