### ISSUE TITLE
Use #!/usr/bin/env perl

### ISSUE THREAD

**Issue by tseemann** [jizhang-nz/fast-GeP#5]
Script is forcing me to use the wrong perl
Please use `#!/usr/bin/env perl` so it uses the one in my PATH
Thank you

**Comment by jizhang-nz** [comment]
Hi tseemann,
Thank you for your comment.
`#!/usr/bin/perl` will use the system-Perl whereas `#!/usr/bin/env perl` will use the Perl designated in the user's PATH.
I couldn't imagine why the system-Perl would be a wrong Perl for fast-GeP? 
Anyway I have never encountered any problem because of the shebang line. Maybe it's because the script does not relay on any external Perl package or module.
Cheers,
Ji

**Comment by tseemann** [comment]
You should never force a particular perl version. I put the perl I want to run in the PATH first because that's the one needed to run. This is critical in systems like `brew` and `conda`.

Not all installations, for example containers (docker etc) have /usr/bin/perl installed as they are based on "lightweight" unix installations.

The shebang line I provide is the standard correct way. It will use system perl if you use all default paths, and the one i need you to use when i have an alternative path. You can't lose.

**Comment by jizhang-nz** [comment]
That's a very good point!
I've changed my code accordingly and will consider this issue resolved.
Cheers,
Ji

**Comment by tseemann** [comment]
Thank you for considering my argument.
And it does make it easier that you use no non-core modules.
